# Generated by Django 5.2.8 on 2025-11-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID цены в Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID продукта в Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ID сессии в Stripe'),
        ),
    ]
