# Generated by Django 5.2.8 on 2025-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_increase_stripe_fields_to_500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_price_id',
            field=models.TextField(blank=True, null=True, verbose_name='ID цены в Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_product_id',
            field=models.TextField(blank=True, null=True, verbose_name='ID продукта в Stripe'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_session_id',
            field=models.TextField(blank=True, null=True, verbose_name='ID сессии в Stripe'),
        ),
    ]
