# Generated by Django 5.2.8 on 2025-11-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_change_stripe_fields_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на оплату Stripe'),
        ),
    ]
